// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class Additive
{
    public int Id { get; set; }

    public string Type { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public int? ConsumptionRate { get; set; }

    public int? GlueSolidContent { get; set; }

    public string Remark { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}