// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class AutoPackingSpec
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string MaterialNo { get; set; }

    public string NPalletType { get; set; }

    public string CPalletArrange { get; set; }

    public string CPalletStackPos { get; set; }

    public string NStrapCompression { get; set; }

    public string CStrapType { get; set; }

    public string NWrapType { get; set; }

    public string NTopBoardType { get; set; }

    public string NBottomBoardType { get; set; }

    public string CStrapperBottomProtection { get; set; }

    public string CStrapperTopProtection { get; set; }

    public string CornerGuard { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}