// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class BoardUse
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string MaterialNo { get; set; }

    public string BoardId { get; set; }

    public string BoardName { get; set; }

    public string Kiwi { get; set; }

    public int Priority { get; set; }

    public bool Active { get; set; }

    public string Flute { get; set; }

    public string Gl { get; set; }

    public string Bm { get; set; }

    public string Bl { get; set; }

    public string Cm { get; set; }

    public string Cl { get; set; }

    public string Dm { get; set; }

    public string Dl { get; set; }

    public double Weight { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}