// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class BoardSpec
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Grade { get; set; }

    public string Station { get; set; }

    public int? Item { get; set; }
}