// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class BoardCombine
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Flute { get; set; }

    public string Board { get; set; }

    public string BoardCombine1 { get; set; }

    public bool? StandardBoard { get; set; }

    public int GroupPaperWidth { get; set; }

    public double? Weight { get; set; }

    public double Thickness { get; set; }

    public double? StandardCost { get; set; }

    public string Kiwi { get; set; }

    public string CorrControl { get; set; }

    public int? Strength { get; set; }

    public double? Ectstrength { get; set; }

    public double? Fctstrength { get; set; }

    public double? Burst { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}