// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class BoardCombineAcc
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string Code { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public double? Biwall { get; set; }

    public double? C1arta35 { get; set; }

    public double? C1copb00 { get; set; }

    public double? C1copbc0 { get; set; }

    public double? C1copc00 { get; set; }

    public double? C1cope00 { get; set; }

    public double? C1dupd30 { get; set; }

    public double? C1dupd40 { get; set; }

    public double? C1hnch20 { get; set; }

    public double? C1ppbp03 { get; set; }

    public double? C1ppbp05 { get; set; }

    public double? C1stks00 { get; set; }

    public double? C1stks01 { get; set; }

    public double? C2copb00 { get; set; }

    public double? C2copbc0 { get; set; }

    public double? C2copc00 { get; set; }

    public double? C2cope00 { get; set; }

    public double? C2hnch20 { get; set; }

    public double? C2stks00 { get; set; }

    public double? C3copb00 { get; set; }

    public double? C3copbc0 { get; set; }

    public double? C3copc00 { get; set; }

    public double? C3cope00 { get; set; }

    public double? C3hnch10 { get; set; }

    public double? C3hnch15 { get; set; }

    public double? C3hnch20 { get; set; }

    public double? C3stks00 { get; set; }

    public double? Ca { get; set; }

    public double? Cb { get; set; }

    public double? Cc { get; set; }

    public double? Cf { get; set; }

    public double? Cg { get; set; }

    public double? Cl { get; set; }

    public double? Cp { get; set; }

    public double? Cs { get; set; }

    public double? Ct { get; set; }

    public double? Cw { get; set; }

    public double? D0arta35 { get; set; }

    public double? D0copb00 { get; set; }

    public double? D0copbc0 { get; set; }

    public double? D0copc00 { get; set; }

    public double? D0cope00 { get; set; }

    public double? D0dupd30 { get; set; }

    public double? D0hnch20 { get; set; }

    public double? D0stks00 { get; set; }

    public double? D1arta35 { get; set; }

    public double? D1copb00 { get; set; }

    public double? D1copbc0 { get; set; }

    public double? D1copc00 { get; set; }

    public double? D1cope00 { get; set; }

    public double? D1dupd30 { get; set; }

    public double? D1dupd40 { get; set; }

    public double? D1hnch20 { get; set; }

    public double? D1ppbp05 { get; set; }

    public double? D1stks00 { get; set; }

    public double? D1stks01 { get; set; }

    public double? D2copb00 { get; set; }

    public double? D2copbc0 { get; set; }

    public double? D2hnch20 { get; set; }

    public double? D3copb00 { get; set; }

    public double? D3copbc0 { get; set; }

    public double? D3hnch10 { get; set; }

    public double? D3hnch15 { get; set; }

    public double? D3hnch20 { get; set; }

    public double? D3ptww05 { get; set; }

    public double? D4arta35 { get; set; }

    public double? D4copb00 { get; set; }

    public double? D4copbc0 { get; set; }

    public double? D4cope00 { get; set; }

    public double? D4dupd30 { get; set; }

    public double? D4dupd40 { get; set; }

    public double? D4ppbp05 { get; set; }

    public double? D5copb00 { get; set; }

    public double? D5copbc0 { get; set; }

    public double? D6copb00 { get; set; }

    public double? D6copbc0 { get; set; }

    public double? D6hnch20 { get; set; }

    public double? D6ptww05 { get; set; }

    public double? D7arta35 { get; set; }

    public double? D7copb00 { get; set; }

    public double? D7copbc0 { get; set; }

    public double? D7cope00 { get; set; }

    public double? D7dupd30 { get; set; }

    public double? D7dupd40 { get; set; }

    public double? D8copb00 { get; set; }

    public double? D8copbc0 { get; set; }

    public double? D9copb00 { get; set; }

    public double? D9copbc0 { get; set; }

    public double? Dbstddlp { get; set; }

    public double? Dbstddpa { get; set; }

    public double? Dbstddps { get; set; }

    public double? Dbstddsa { get; set; }

    public double? Dbnondlp { get; set; }

    public double? Dbnondpa { get; set; }

    public double? Dbnondps { get; set; }

    public double? Dbnondsa { get; set; }

    public double? Ddm14dlp { get; set; }

    public double? Ddm14dpa { get; set; }

    public double? Ddm14dps { get; set; }

    public double? Ddm14dsa { get; set; }

    public double? Ddm23dlp { get; set; }

    public double? Ddm23dpa { get; set; }

    public double? Ddm23dps { get; set; }

    public double? Ddm23dsa { get; set; }

    public double? Ddm40dlp { get; set; }

    public double? Ddm40dpa { get; set; }

    public double? Ddm40dps { get; set; }

    public double? Ddm40dsa { get; set; }

    public double? Ddmlwdlp { get; set; }

    public double? Ddmlwdpa { get; set; }

    public double? Ddmlwdps { get; set; }

    public double? Ddmlwdsa { get; set; }

    public double? Diecut { get; set; }

    public double? DiecutPaint { get; set; }

    public double? Drstddlp { get; set; }

    public double? Drstddpa { get; set; }

    public double? Drstddps { get; set; }

    public double? Drstddsa { get; set; }

    public double? Drnondlp { get; set; }

    public double? Drnondpa { get; set; }

    public double? Drnondps { get; set; }

    public double? Drnondsa { get; set; }

    public double? Dsm40dps { get; set; }

    public double? F1copb02 { get; set; }

    public double? F1copc02 { get; set; }

    public double? F1cope02 { get; set; }

    public double? F2copbc2 { get; set; }

    public double? Fc { get; set; }

    public double? Fcf00 { get; set; }

    public double? Fcf01 { get; set; }

    public double? Fcf02 { get; set; }

    public double? Fcf04 { get; set; }

    public double? Fcf10 { get; set; }

    public double? Fcf30 { get; set; }

    public double? H1 { get; set; }

    public double? H2 { get; set; }

    public double? H3 { get; set; }

    public double? H4 { get; set; }

    public double? H5h20 { get; set; }

    public double? H5h35 { get; set; }

    public double? H5h50 { get; set; }

    public double? Ho { get; set; }

    public double? Ht { get; set; }

    public double? Jumbo { get; set; }

    public double? Kr { get; set; }

    public double? Krr00 { get; set; }

    public double? Krr01 { get; set; }

    public double? Krr02 { get; set; }

    public double? Krr04 { get; set; }

    public double? Krr10 { get; set; }

    public double? Krr30 { get; set; }

    public double? Ks { get; set; }

    public double? Kss00 { get; set; }

    public double? Kss01 { get; set; }

    public double? Kss02 { get; set; }

    public double? Kss04 { get; set; }

    public double? Kss10 { get; set; }

    public double? Kss30 { get; set; }

    public double? L1 { get; set; }

    public double? L2 { get; set; }

    public double? L3 { get; set; }

    public double? L4 { get; set; }

    public double? Lc { get; set; }

    public double? Lm { get; set; }

    public double? Mam14 { get; set; }

    public double? Mam23 { get; set; }

    public double? Mam40 { get; set; }

    public double? Mamlw { get; set; }

    public double? Mbm14 { get; set; }

    public double? Mbm23 { get; set; }

    public double? Mbm40 { get; set; }

    public double? Mbmlw { get; set; }

    public double? Mcmlwdlp { get; set; }

    public double? Mcmlwdpa { get; set; }

    public double? Mcmlwdps { get; set; }

    public double? Mcmlwdsa { get; set; }

    public double? Mcm14dlp { get; set; }

    public double? Mcm14dpa { get; set; }

    public double? Mcm14dps { get; set; }

    public double? Mcm14dsa { get; set; }

    public double? Mcm23dlp { get; set; }

    public double? Mcm23dpa { get; set; }

    public double? Mcm23dps { get; set; }

    public double? Mcm23dsa { get; set; }

    public double? Mcm40dlp { get; set; }

    public double? Mcm40dpa { get; set; }

    public double? Mcm40dps { get; set; }

    public double? Mcm40dsa { get; set; }

    public double? Md { get; set; }

    public double? Mf { get; set; }

    public double? Mh { get; set; }

    public double? Mm { get; set; }

    public double? Mnm14 { get; set; }

    public double? Mnm23 { get; set; }

    public double? Mnm40 { get; set; }

    public double? Mnmlw { get; set; }

    public double? Mom14 { get; set; }

    public double? Mom23 { get; set; }

    public double? Mom28 { get; set; }

    public double? Mom40 { get; set; }

    public double? Momlw { get; set; }

    public double? Mp { get; set; }

    public double? Mr { get; set; }

    public double? Ms { get; set; }

    public double? Mt { get; set; }

    public double? O1 { get; set; }

    public double? O2 { get; set; }

    public double? Ol { get; set; }

    public double? Olo00 { get; set; }

    public double? Olo01 { get; set; }

    public double? Olo02 { get; set; }

    public double? Olo04 { get; set; }

    public double? Olo10 { get; set; }

    public double? Olo30 { get; set; }

    public double? PaperPallet { get; set; }

    public double? Partition { get; set; }

    public double? Pb { get; set; }

    public double? Pd { get; set; }

    public double? Ph { get; set; }

    public double? Ps { get; set; }

    public double? Rc { get; set; }

    public double? Rh { get; set; }

    public double? Rotary { get; set; }

    public double? Rp { get; set; }

    public double? Rs { get; set; }

    public double? Rsc { get; set; }

    public double? Rw { get; set; }

    public double? Sb { get; set; }

    public double? Sf { get; set; }

    public double? T1t00 { get; set; }

    public double? T1t01 { get; set; }

    public double? T1t02 { get; set; }

    public double? T1t04 { get; set; }

    public double? T1t10 { get; set; }

    public double? T1t30 { get; set; }

    public double? T2t00 { get; set; }

    public double? T2t01 { get; set; }

    public double? T2t02 { get; set; }

    public double? T2t04 { get; set; }

    public double? T2t10 { get; set; }

    public double? T2t30 { get; set; }

    public double? T3 { get; set; }

    public double? T4 { get; set; }

    public double? Tb { get; set; }

    public double? Tp { get; set; }

    public double? To001 { get; set; }

    public double? To002 { get; set; }

    public double? To003 { get; set; }

    public double? To004 { get; set; }

    public double? To005 { get; set; }

    public double? To006 { get; set; }

    public double? To007 { get; set; }

    public double? To008 { get; set; }

    public double? To009 { get; set; }

    public double? To010 { get; set; }

    public double? To011 { get; set; }

    public double? To012 { get; set; }

    public double? To013 { get; set; }

    public double? To014 { get; set; }

    public double? To015 { get; set; }

    public double? To018 { get; set; }

    public double? To019 { get; set; }

    public double? To020 { get; set; }

    public double? To021 { get; set; }

    public double? Triwall { get; set; }

    public double? Wc { get; set; }

    public double? Wm { get; set; }

    public double? Ws { get; set; }

    public double? Wz { get; set; }

    public double? Z1 { get; set; }

    public double? Z2 { get; set; }

    public double? C2 { get; set; }

    public double? Dcgcw { get; set; }

    public double? Dfgcw { get; set; }

    public double? JumboGcw { get; set; }

    public double? PartitionGcw { get; set; }

    public double? Pbgcw { get; set; }

    public double? Pdgcw { get; set; }

    public double? Psgcw { get; set; }

    public double? Rdgcw { get; set; }

    public double? Rscgcw { get; set; }

    public double? Sbgcw { get; set; }

    public double? S3 { get; set; }

    public double? Pa { get; set; }

    public double? Pc { get; set; }

    public double? Pt { get; set; }
}