// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class BomStruct
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string MaterialNo { get; set; }

    public string Plant { get; set; }

    public string BomUsage { get; set; }

    public double? WeighBom { get; set; }

    public int? PreviousBom { get; set; }

    public string Follower { get; set; }

    public int? Amount { get; set; }

    public string Unit { get; set; }

    public string PdisStatus { get; set; }

    public bool TranStatus { get; set; }

    public bool SapStatus { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}