// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class Coating
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string MaterialNo { get; set; }

    public string Station { get; set; }

    public string Slide { get; set; }

    public int? Layer { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }
}