// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class Color
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string Ink { get; set; }

    public string Shade { get; set; }

    public int? Darkness { get; set; }

    public string MainDensity { get; set; }

    public bool? IsMainColor { get; set; }

    public bool? OptDelete { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}