// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class ConfigWordingReport
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string Wording { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }
}