// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string CusId { get; set; }

    public string CustName { get; set; }

    public string CustCode { get; set; }

    public string CustomerGroup { get; set; }

    public string SoldToCode { get; set; }

    public string Accgroup { get; set; }

    public string Cust { get; set; }

    public string IndGrp { get; set; }

    public string District { get; set; }

    public string Zone { get; set; }

    public string Route { get; set; }

    public string CustClass { get; set; }

    public string CustReq { get; set; }

    public string CustAlert { get; set; }

    public int? PriorityFlag { get; set; }

    public bool? CustStatus { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public int? PalletOverhang { get; set; }

    public string Qaspec { get; set; }

    public string DataFrom { get; set; }

    public string TagBundle { get; set; }

    public string TagPallet { get; set; }

    public string NoTagBundle { get; set; }

    public string HeadTagBundle { get; set; }

    public string FootTagBundle { get; set; }

    public string HeadTagPallet { get; set; }

    public string FootTagPallet { get; set; }

    public string FlagRouting { get; set; }

    public bool Coa { get; set; }

    public bool Film { get; set; }

    public string Freetext1TagBundle { get; set; }

    public string Freetext2TagBundle { get; set; }

    public string Freetext3TagBundle { get; set; }

    public string Freetext1TagPallet { get; set; }

    public string Freetext2TagPallet { get; set; }

    public string Freetext3TagPallet { get; set; }
}