// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class CustShipTo
{
    public int Id { get; set; }

    public int Seq { get; set; }

    public string ShipTo { get; set; }

    public string CustCode { get; set; }

    public string TransportZone { get; set; }

    public int? DeliveryDistance { get; set; }

    public DateTime? DeliveryTime { get; set; }

    public DateTime? CustPreWait { get; set; }

    public DateTime? CustPostWait { get; set; }

    public string CustRecvTime { get; set; }
}