// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class CustomerSkic
{
    public int Id { get; set; }

    public string CustomerNo { get; set; }

    public string SalesOrg { get; set; }

    public string DistributionChannel { get; set; }

    public string Remark { get; set; }
}