// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class DocumentSlist
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string Snumber { get; set; }

    public string OrderItem { get; set; }

    public string Pc { get; set; }

    public string MaterialNo { get; set; }

    public string MatDesc { get; set; }

    public string CustomerName { get; set; }

    public string Flute { get; set; }

    public DateTime? DuedateOld { get; set; }

    public DateTime? DuedateNew { get; set; }

    public int? OrderQtyOld { get; set; }

    public int? OrderQtyNew { get; set; }

    public bool? Cancel { get; set; }

    public bool? Hold { get; set; }

    public string BoxStatus { get; set; }

    public string PartStatus { get; set; }

    public string Process { get; set; }

    public string Remark { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}