// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class EorderingLog
{
    public int Id { get; set; }

    public string RequestId { get; set; }

    public string MaterialNo { get; set; }

    public bool? StatusResponse { get; set; }

    public string StatusMessage { get; set; }

    public string SentBy { get; set; }

    public DateTime? SentDate { get; set; }
    public string JsonRequestBody { get; set; }
}