// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class FluteLayer
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Tr { get; set; }

    public int? Layer { get; set; }
}