// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class HierarchyLv2Matrix
{
    public int Id { get; set; }

    public string HierarchyLv2Code { get; set; }

    public int? IdKindOfProductGroup { get; set; }

    public int? IdProcessCost { get; set; }

    public int? IdKindOfProduct { get; set; }

    public int? IdProductType { get; set; }

    public bool? Status { get; set; }

    public int? SortIndex { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}