// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class HireOrder
{
    public int Id { get; set; }

    public string OrderType { get; set; }

    public int? EmployerChannel { get; set; }

    public int? EmployeeChannel { get; set; }

    public bool? SyncMat { get; set; }
}