// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class HireMapping
{
    public int Id { get; set; }

    public int? GroupBu { get; set; }

    public int? OrderId { get; set; }
}