// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class HoldMaterial
{
    public int Id { get; set; }

    public string MaterialNo { get; set; }

    public bool? IsLocked { get; set; }

    public string HoldRemark { get; set; }

    public string ChangeProductNo { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}