// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class HoneyPaper
{
    public string Grade { get; set; }

    public int? Weight { get; set; }

    public int? PaperAmt { get; set; }

    public int? Stretch { get; set; }

    public double? Shrink { get; set; }

    public double? SolidContent { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}