// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class HvaMaster
{
    public int Id { get; set; }

    public int Seq { get; set; }

    public string HighGroup { get; set; }

    public string HighGroupName { get; set; }

    public string HighValue { get; set; }

    public string HighDescription { get; set; }

    public decimal? Weight { get; set; }

    public string Flag { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}