// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class InfoRecordSourceList
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string Vendorcode { get; set; }

    public string Vendorname { get; set; }

    public string Materialno { get; set; }

    public string Purorg { get; set; }

    public string Plant { get; set; }

    public string Purgroup { get; set; }

    public decimal? Stdqty { get; set; }

    public string Unitofstdqty { get; set; }

    public decimal? Minqty { get; set; }

    public string Unitofminqty { get; set; }

    public decimal? Percentover { get; set; }

    public decimal? Percentunder { get; set; }

    public string Taxcode { get; set; }

    public decimal? Netprice { get; set; }

    public string Unitofnetprice { get; set; }

    public decimal? Priceunit { get; set; }

    public string Unit { get; set; }

    public decimal? Effprice { get; set; }

    public DateTime? Validto { get; set; }

    public string Incoterm { get; set; }

    public DateTime? SourcelistValidfrom { get; set; }

    public DateTime? SourcelistValidto { get; set; }

    public string Fixed { get; set; }

    public int Nosourcelist { get; set; }

    public DateTime? RecordedDate { get; set; }
}