// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MachineGroup
{
    public int Id { get; set; }

    public string GroupCode { get; set; }

    public string GroupName { get; set; }

    public string GroupDescription { get; set; }

    public int? SortIndex { get; set; }
}