// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MapCost
{
    public int Id { get; set; }

    public string Hierarchy2 { get; set; }

    public string Hierarchy3 { get; set; }

    public string Hierarchy4 { get; set; }

    public string CostField { get; set; }

    public string Description { get; set; }

    public bool? Active { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}