// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MappingPg
{
    public string Code { get; set; }

    public string Description { get; set; }

    public string Desc { get; set; }

    public string Map { get; set; }
}