// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MasterRole
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public string RoleDesc { get; set; }
}