// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MaterialType
{
    public int Id { get; set; }

    public string MatCode { get; set; }

    public string GroupId { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Production BOM and Salels BOM
    /// </summary>
    public bool? BomMaster { get; set; }

    public bool? Interface { get; set; }

    public bool? Inventory { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}