// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MenuRole
{
    public int Id { get; set; }

    public int? IdMenu { get; set; }

    public int? IdRole { get; set; }

    public int? SortMenu { get; set; }
}