// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MoBomRawMat
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string OrderItem { get; set; }

    public string FgMaterial { get; set; }

    public int? MaterialType { get; set; }

    public string MaterialNumber { get; set; }

    public string Plant { get; set; }

    public string MaterialDescription { get; set; }

    public decimal? NetWeight { get; set; }

    public string MaterialGroup { get; set; }

    public string SizeUom { get; set; }

    public decimal? Width { get; set; }

    public decimal? Length { get; set; }

    public int? Lay { get; set; }

    public int? CutSize { get; set; }

    public decimal? BomAmount { get; set; }

    public string Uom { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string UpdateBy { get; set; }

    public string OldMaterialNumber { get; set; }
}