// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MoSpec
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string OrderItem { get; set; }

    public string MaterialNo { get; set; }

    public string PartNo { get; set; }

    public string Pc { get; set; }

    public string Hierarchy { get; set; }

    public string SaleOrg { get; set; }

    public string Plant { get; set; }

    public string CustCode { get; set; }

    public string CusId { get; set; }

    public string CustName { get; set; }

    public string Description { get; set; }

    public string SaleText1 { get; set; }

    public string SaleText2 { get; set; }

    public string SaleText3 { get; set; }

    public string SaleText4 { get; set; }

    public string Change { get; set; }

    public string Language { get; set; }

    public string IndGrp { get; set; }

    public string IndDes { get; set; }

    public string MaterialType { get; set; }

    public string PrintMethod { get; set; }

    public bool? TwoPiece { get; set; }

    public string Flute { get; set; }

    public string Code { get; set; }

    public string Board { get; set; }

    public string Gl { get; set; }

    public int? Glweigth { get; set; }

    public string Bm { get; set; }

    public int? Bmweigth { get; set; }

    public string Bl { get; set; }

    public int? Blweigth { get; set; }

    public string Cm { get; set; }

    public int? Cmweigth { get; set; }

    public string Cl { get; set; }

    public int? Clweigth { get; set; }

    public string Dm { get; set; }

    public int? Dmweigth { get; set; }

    public string Dl { get; set; }

    public int? Dlweigth { get; set; }

    public int? Wid { get; set; }

    public int? Leg { get; set; }

    public int? Hig { get; set; }

    public string BoxType { get; set; }

    public string RscStyle { get; set; }

    public string ProType { get; set; }

    public string JoinType { get; set; }

    public string StatusFlag { get; set; }

    public string PriorityFlag { get; set; }

    public int? Wire { get; set; }

    public bool? OuterJoin { get; set; }

    public int? CutSheetLeng { get; set; }

    public int? CutSheetWid { get; set; }

    public int? SheetArea { get; set; }

    public int? BoxArea { get; set; }

    public int? ScoreW1 { get; set; }

    public int? Scorew2 { get; set; }

    public int? Scorew3 { get; set; }

    public int? Scorew4 { get; set; }

    public int? Scorew5 { get; set; }

    public int? Scorew6 { get; set; }

    public int? Scorew7 { get; set; }

    public int? Scorew8 { get; set; }

    public int? Scorew9 { get; set; }

    public int? Scorew10 { get; set; }

    public int? Scorew11 { get; set; }

    public int? Scorew12 { get; set; }

    public int? Scorew13 { get; set; }

    public int? Scorew14 { get; set; }

    public int? Scorew15 { get; set; }

    public int? Scorew16 { get; set; }

    public int? JointLap { get; set; }

    public int? ScoreL2 { get; set; }

    public int? ScoreL3 { get; set; }

    public int? ScoreL4 { get; set; }

    public int? ScoreL5 { get; set; }

    public int? ScoreL6 { get; set; }

    public int? ScoreL7 { get; set; }

    public int? ScoreL8 { get; set; }

    public int? ScoreL9 { get; set; }

    public int? Slit { get; set; }

    public int? NoSlot { get; set; }

    public int? Bun { get; set; }

    public int? BunLayer { get; set; }

    public int? LayerPalet { get; set; }

    public int? BoxPalet { get; set; }

    public double? WeightSh { get; set; }

    public double? WeightBox { get; set; }

    public int? SparePercen { get; set; }

    public int? SpareMax { get; set; }

    public int? SpareMin { get; set; }

    public int? LeadTime { get; set; }

    public int? PieceSet { get; set; }

    public string SaleUom { get; set; }

    public string BomUom { get; set; }

    public int? Hardship { get; set; }

    public string PalletSize { get; set; }

    public string PalletizationPath { get; set; }

    public string PrintMasterPath { get; set; }

    public string DiecutPictPath { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? LastUpdate { get; set; }

    public string User { get; set; }

    public int? PltLegDouble { get; set; }

    public int? PltDoubleAxle { get; set; }

    public int? PltLegSingle { get; set; }

    public int? PltSingleAxle { get; set; }

    public int? PltFloorAbove { get; set; }

    public int? PltFloorUnder { get; set; }

    public int? PltBeam { get; set; }

    public int? PltAxleHeight { get; set; }

    public string EanCode { get; set; }

    public bool? NewH { get; set; }

    public string HighGroup { get; set; }

    public string HighValue { get; set; }

    public string ChangeInfo { get; set; }

    public int? PiecePatch { get; set; }

    public bool? BoxHandle { get; set; }

    public string PsmId { get; set; }

    public string PicPallet { get; set; }

    public string ChangeHistory { get; set; }

    public string CustComment { get; set; }

    public string MaterialComment { get; set; }

    public decimal? CutSheetWidInch { get; set; }

    public decimal? CutSheetLengInch { get; set; }

    public string JointId { get; set; }

    public string CustInvType { get; set; }

    public string CipinvType { get; set; }

    public string FgMaterial { get; set; }

    public string TopSheetMaterial { get; set; }

    public string JoinCharacter { get; set; }

    public string FgpicPath { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string PdisStatus { get; set; }

    public bool TranStatus { get; set; }

    public bool SapStatus { get; set; }

    public string PurTxt1 { get; set; }

    public string PurTxt2 { get; set; }

    public string PurTxt3 { get; set; }

    public string PurTxt4 { get; set; }

    public bool? UnUpgradBoard { get; set; }

    public bool? IsTransfer { get; set; }

    public string AttachFileMoPath { get; set; }

    public string MatCopy { get; set; }

    public int? Perforate1 { get; set; }

    public int? Perforate2 { get; set; }

    public int? Perforate3 { get; set; }

    public int? Perforate4 { get; set; }

    public int? Perforate5 { get; set; }

    public int? Perforate6 { get; set; }

    public int? Perforate7 { get; set; }

    public int? Perforate8 { get; set; }

    public int? Perforate9 { get; set; }

    public int? Perforate10 { get; set; }

    public int? Perforate11 { get; set; }

    public int? Perforate12 { get; set; }

    public int? Perforate13 { get; set; }

    public int? Perforate14 { get; set; }

    public int? Perforate15 { get; set; }

    public int? Perforate16 { get; set; }

    public string Semi1Path { get; set; }

    public string Semi2Path { get; set; }

    public string Semi3Path { get; set; }

    public string SemiFilePdfPath { get; set; }

    public bool NoneStandardPaper { get; set; }

    public string TagBundle { get; set; }

    public string TagPallet { get; set; }

    public string NoTagBundle { get; set; }

    public string HeadTagBundle { get; set; }

    public string FootTagBundle { get; set; }

    public string HeadTagPallet { get; set; }

    public string FootTagPallet { get; set; }

    public int? PerforateGap { get; set; }

    public string FluteDesc { get; set; }

    public string Freetext1TagBundle { get; set; }

    public string Freetext2TagBundle { get; set; }

    public string Freetext3TagBundle { get; set; }

    public string Freetext1TagPallet { get; set; }

    public string Freetext2TagPallet { get; set; }

    public string Freetext3TagPallet { get; set; }

    public string SboExternalNumber { get; set; }

    public string HireFactory { get; set; }
}