// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class MoTemp
{
    public int Id { get; set; }

    public string SaleOrg { get; set; }

    public string Plant { get; set; }

    public string MoStatus { get; set; }

    public string OrderItem { get; set; }

    public string MaterialNo { get; set; }

    public string Name { get; set; }

    public string OrderQuant { get; set; }

    public string ToleranceOver { get; set; }

    public string ToleranceUnder { get; set; }

    public string DueDate { get; set; }

    public string TargetQuant { get; set; }

    public string ItemNote { get; set; }

    public string District { get; set; }

    public string PoNo { get; set; }

    public string DateTimeStamp { get; set; }

    public string Batch { get; set; }

    public string Board { get; set; }

    public string CutSheetWid { get; set; }

    public string CutSheetLeng { get; set; }

    public string Hig { get; set; }

    public string ScoreW1 { get; set; }

    public string ScoreW2 { get; set; }

    public string ScoreW3 { get; set; }

    public string ScoreW4 { get; set; }

    public string ScoreW5 { get; set; }

    public string ScoreW6 { get; set; }

    public string SoldTo { get; set; }

    public string ShipTo { get; set; }
}