// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class Pallet
{
    public int Id { get; set; }

    public double? PalletWidth { get; set; }

    public double? PalletLength { get; set; }

    public string PalletType { get; set; }

    public string PalletOwner { get; set; }

    public double? PalletHeight { get; set; }

    public string PalletPatterns { get; set; }

    public double? OverhangWidth { get; set; }

    public double? OverhangLength { get; set; }
}