// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PaperWidth
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public int Group1 { get; set; }

    public int? Group2 { get; set; }

    public int? Group3 { get; set; }

    public int? Group4 { get; set; }

    public int Width { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}