// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PlantView
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string MaterialNo { get; set; }

    public string Plant { get; set; }

    public string PurchCode { get; set; }

    public string ShipBlk { get; set; }

    public double StdTotalCost { get; set; }

    public double StdVc { get; set; }

    public double StdFc { get; set; }

    public double StdMovingCost { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public string PdisStatus { get; set; }

    public bool TranStatus { get; set; }

    public bool SapStatus { get; set; }
}