// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PlantCostField
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string CostField { get; set; }

    public int? Sort { get; set; }
}