// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PpcBoiStatus
{
    public int Id { get; set; }

    public string Status { get; set; }
}