// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PpcFscCode
{
    public int Id { get; set; }

    public string FscCode { get; set; }

    public string FscProductType { get; set; }

    public string FscSalesText { get; set; }
}