// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PpcFscFgCode
{
    public int Id { get; set; }

    public string FscFgCode { get; set; }

    public string FscFgDescription { get; set; }

    public string FscFgPrefix { get; set; }

    public int? Length { get; set; }

    public int? Running { get; set; }
}