// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PpcMasterRpac
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string RpacCode { get; set; }

    public string RpacName { get; set; }

    public string DimensionCode { get; set; }

    public int? GlobalDimensionNo { get; set; }
}