// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PresaleChangeRouting
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string PsmId { get; set; }

    public int? SeqNo { get; set; }

    public string MaterialNo { get; set; }

    public string MatCode { get; set; }

    public string PlanCode { get; set; }

    public string Machine { get; set; }

    public string Color1 { get; set; }

    public string Shade1 { get; set; }

    public string Color2 { get; set; }

    public string Shade2 { get; set; }

    public string Color3 { get; set; }

    public string Shade3 { get; set; }

    public string Color4 { get; set; }

    public string Shade4 { get; set; }

    public string Color5 { get; set; }

    public string Shade5 { get; set; }

    public string Color6 { get; set; }

    public string Shade6 { get; set; }

    public string Color7 { get; set; }

    public string Shade7 { get; set; }

    public bool? IsApprove { get; set; }
}