// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class PricingMasterScale
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string ConditionType { get; set; }

    public string SalesOrg { get; set; }

    public string DistributionChannel { get; set; }

    public string MaterialNo { get; set; }

    public DateTime ValidityEndDate { get; set; }

    public string ConditionNumber { get; set; }

    public double Rate { get; set; }

    public string CurrencyKey { get; set; }

    public int? ConditionPricingUnit { get; set; }

    public string Uom { get; set; }

    public DateTime ValidityStartFrom { get; set; }

    public int ScaleQuantity { get; set; }

    public string DataFrom { get; set; }
}