// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class ProductType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public int? SortIndex { get; set; }

    public string HierarchyLv2 { get; set; }

    public string UnitDesc { get; set; }

    public int? UnitDefault { get; set; }

    public string FormGroup { get; set; }

    public int? BoardMoDisplay { get; set; }

    public bool? IsTwoPiece { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool BoxHandle { get; set; }

    public string FlexoOrderBy { get; set; }

    public string Dc { get; set; }
}