// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class ProductCatalogConfig
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string UserName { get; set; }

    public string ColumnName { get; set; }
}