// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class QaAlertTemp
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public long? AlertEventId { get; set; }

    public string MaterialNo { get; set; }

    public string SalesOrg { get; set; }

    public string MachineCode { get; set; }

    public string WarnId { get; set; }

    public string WarnMessage1 { get; set; }

    public string WarnMessage2 { get; set; }

    public bool Flag { get; set; }
}