// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class Remark
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string Pc { get; set; }

    public string Remark1 { get; set; }

    public int? NonMove { get; set; }

    public DateTime? NonMoveMonth { get; set; }

    public int? StockWip { get; set; }

    public int? StockFg { get; set; }

    public int? StockQa { get; set; }

    public DateTime? LastUpdate { get; set; }

    public string UpdateBy { get; set; }
}