// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class RunningNo
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string Company { get; set; }

    public string Plant { get; set; }

    public string GroupId { get; set; }

    public int ScopeNo { get; set; }

    public int Length { get; set; }

    public int StartNo { get; set; }

    public int EndNo { get; set; }

    public string Fix { get; set; }

    public int Running { get; set; }

    public string Holder { get; set; }

    public DateOnly? DateStamp { get; set; }

    public bool? Active { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}