// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class SalesView
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string MaterialNo { get; set; }

    public string SaleOrg { get; set; }

    public int Channel { get; set; }

    public string CustCode { get; set; }

    public string DevPlant { get; set; }

    public int? MinQty { get; set; }

    public double? SaleUnitPrice { get; set; }

    public string OrderType { get; set; }

    public double? PriceAdj { get; set; }

    public double? OldPrice { get; set; }

    public double? NewPrice { get; set; }

    public DateTime? Effective { get; set; }

    public DateTime? ChangeDate { get; set; }

    public string PdisStatus { get; set; }

    public bool TranStatus { get; set; }

    public bool SapStatus { get; set; }
}