// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class ScoreGap
{
    public int Id { get; set; }

    public string FactoryCode { get; set; }

    public string Flute { get; set; }

    public string ScoreType { get; set; }

    public double? ScoreGap1 { get; set; }

    public string ControllerCode { get; set; }

    public string PlanProgramCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}