// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class SetCategoriesOldMat
{
    public int IdProductType { get; set; }

    public string PdtName { get; set; }

    public string Lv2 { get; set; }

    public int? IdKindOfProductGroup { get; set; }

    public string KpgName { get; set; }

    public int? IdProcessCost { get; set; }

    public string PccName { get; set; }

    public int? IdKindOfProduct { get; set; }

    public string KopName { get; set; }
}