// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class StandardPatternName
{
    public int Id { get; set; }

    public string PatternName { get; set; }

    public string Type { get; set; }

    public int? Amount { get; set; }

    public int? Col { get; set; }

    public int? Row { get; set; }

    /// <summary>
    /// ชื่อรูปจาก PM2 เช่น Type01.jpg,Type2.jpg
    /// </summary>
    public string PictureNamePallet { get; set; }

    public string Picturepath { get; set; }

    public bool Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime UpdatedTime { get; set; }

    public string UpdateBy { get; set; }
}