// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class SubMenus
{
    public int Id { get; set; }

    public string SubMenuName { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public int MainMenuId { get; set; }
    public int SeqNo{get; set;}
}