// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMTs.DataAccess.Models;

public partial class UpdateDuedateAndOrderQtyByDwtoMoData
{
    public int Id { get; set; }

    public string SalesDocumentNo { get; set; }

    public string ItemNo { get; set; }

    public int? SalesQty { get; set; }

    public DateTime? DueDate { get; set; }

    public string SalesDocumentNoItemNo { get; set; }
}