using System;

namespace PMTs.DataAccess.ModelPresale
{
    public partial class PresaleMasterData
    {
        public string PsmId { get; set; }
        public string PsmStatus { get; set; }
        public string MaterialNo { get; set; }
        public string PartNo { get; set; }
        public string Pc { get; set; }
        public string Hierarchy { get; set; }
        public string SaleOrg { get; set; }
        public string Plant { get; set; }
        public string CustCode { get; set; }
        public string CusId { get; set; }
        public string CustName { get; set; }
        public string Description { get; set; }
        public string SaleText1 { get; set; }
        public string SaleText2 { get; set; }
        public string SaleText3 { get; set; }
        public string SaleText4 { get; set; }
        public string Change { get; set; }
        public string Language { get; set; }
        public string IndGrp { get; set; }
        public string IndDes { get; set; }
        public string MaterialType { get; set; }
        public string PrintMethod { get; set; }
        public bool? TwoPiece { get; set; }
        public string Flute { get; set; }
        public string Code { get; set; }
        public string Board { get; set; }
        public string Gl { get; set; }
        public int? Glweigth { get; set; }
        public string Bm { get; set; }
        public int? Bmweigth { get; set; }
        public string Bl { get; set; }
        public int? Blweigth { get; set; }
        public string Cm { get; set; }
        public int? Cmweigth { get; set; }
        public string Cl { get; set; }
        public int? Clweigth { get; set; }
        public string Dm { get; set; }
        public int? Dmweigth { get; set; }
        public string Dl { get; set; }
        public int? Dlweigth { get; set; }
        public int? Wid { get; set; }
        public int? Leg { get; set; }
        public int? Hig { get; set; }
        public string BoxType { get; set; }
        public string RscStyle { get; set; }
        public string ProType { get; set; }
        public string JoinType { get; set; }
        public string StatusFlag { get; set; }
        public string PriorityFlag { get; set; }
        public byte? Wire { get; set; }
        public bool? OuterJoin { get; set; }
        public int? CutSheetLeng { get; set; }
        public int? CutSheetWid { get; set; }
        public int? SheetArea { get; set; }
        public int? BoxArea { get; set; }
        public int? ScoreW1 { get; set; }
        public int? Scorew2 { get; set; }
        public int? Scorew3 { get; set; }
        public int? Scorew4 { get; set; }
        public int? Scorew5 { get; set; }
        public int? Scorew6 { get; set; }
        public int? Scorew7 { get; set; }
        public int? Scorew8 { get; set; }
        public int? Scorew9 { get; set; }
        public int? Scorew10 { get; set; }
        public int? Scorew11 { get; set; }
        public int? Scorew12 { get; set; }
        public int? Scorew13 { get; set; }
        public int? Scorew14 { get; set; }
        public int? Scorew15 { get; set; }
        public int? Scorew16 { get; set; }
        public byte? JointLap { get; set; }
        public int? ScoreL2 { get; set; }
        public int? ScoreL3 { get; set; }
        public int? ScoreL4 { get; set; }
        public int? ScoreL5 { get; set; }
        public int? ScoreL6 { get; set; }
        public int? ScoreL7 { get; set; }
        public int? ScoreL8 { get; set; }
        public int? ScoreL9 { get; set; }
        public byte? Slit { get; set; }
        public int? NoSlot { get; set; }

        public int? Bun { get; set; }
        public int? BunLayer { get; set; }
        public int? LayerPalet { get; set; }
        public int? BoxPalet { get; set; }
        public double? WeightSh { get; set; }
        public double? WeightBox { get; set; }
        public int? SparePercen { get; set; }
        public int? SpareMax { get; set; }
        public int? SpareMin { get; set; }
        public byte? LeadTime { get; set; }
        public int? PieceSet { get; set; }
        public string SaleUom { get; set; }
        public string BomUom { get; set; }
        public int? Hardship { get; set; }
        public string PalletSize { get; set; }
        public string PalletizationPath { get; set; }
        public string PrintMasterPath { get; set; }
        public string DiecutPictPath { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? LastUpdate { get; set; }
        public string User { get; set; }
        public int? PltLegDouble { get; set; }
        public int? PltDoubleAxle { get; set; }
        public int? PltLegSingle { get; set; }
        public int? PltSingleAxle { get; set; }
        public byte? PltFloorAbove { get; set; }
        public byte? PltFloorUnder { get; set; }
        public byte? PltBeam { get; set; }
        public byte? PltAxleHeight { get; set; }
        public string EanCode { get; set; }
        public string PdisStatus { get; set; }
        public bool TranStatus { get; set; }
        public bool SapStatus { get; set; }
        public bool? NewH { get; set; }
        public string PurTxt1 { get; set; }
        public string PurTxt2 { get; set; }
        public string PurTxt3 { get; set; }
        public string PurTxt4 { get; set; }
        public bool? UnUpgradBoard { get; set; }
        public string HighGroup { get; set; }
        public string HighValue { get; set; }
        public string FlagChange { get; set; }
        public string PsAwfile { get; set; }
        public string PsDwFile { get; set; }
        public string PsLpFile { get; set; }
        public string PsPoFile { get; set; }
        public string PsQtFile { get; set; }
        public string PsOtherFile { get; set; }
        public string CustComment { get; set; }
        public string MaterialComment { get; set; }
        public string JoinCharacter { get; set; }
        public string ProcessCost { get; set; }
        public string PsPvFile { get; set; }
        public string PsAllFile { get; set; }

    }
}
