using PMTs.DataAccess.Models;
using System.Collections.Generic;

namespace PMTs.DataAccess.ModelView.Report
{
    public class CloneRouting
    {
        public int Id { get; set; }
        public string FactoryCode { get; set; }
        public int SeqNo { get; set; }
        public string Plant { get; set; }
        public string MaterialNo { get; set; }
        public string MatCode { get; set; }
        public string PlanCode { get; set; }
        public string Machine { get; set; }
        public string Alternative1 { get; set; }
        public string Alternative2 { get; set; }
        public bool? StdProcess { get; set; }
        public int? Speed { get; set; }
        public int? ColourCount { get; set; }
        public bool? McMove { get; set; }
        public bool? HandHold { get; set; }
        public string PlateNo { get; set; }
        public string MylaNo { get; set; }
        public int? PaperWidth { get; set; }
        public int? CutNo { get; set; }
        public int? Trim { get; set; }
        public double? PercenTrim { get; set; }
        public int? WasteLeg { get; set; }
        public int? WasteWid { get; set; }
        public int? SheetInLeg { get; set; }
        public int? SheetInWid { get; set; }
        public int? SheetOutLeg { get; set; }
        public int? SheetOutWid { get; set; }
        public double? WeightIn { get; set; }
        public double? WeightOut { get; set; }
        public int? NoOpenIn { get; set; }
        public int? NoOpenOut { get; set; }
        public string Color1 { get; set; }
        public string Shade1 { get; set; }
        public string Color2 { get; set; }
        public string Shade2 { get; set; }
        public string Color3 { get; set; }
        public string Shade3 { get; set; }
        public string Color4 { get; set; }
        public string Shade4 { get; set; }
        public string Color5 { get; set; }
        public string Shade5 { get; set; }
        public string Color6 { get; set; }
        public string Shade6 { get; set; }
        public string Color7 { get; set; }
        public string Shade7 { get; set; }
        public string Color8 { get; set; }
        public string Shade8 { get; set; }
        public string Color9 { get; set; }
        public string Shade9 { get; set; }
        public string Color10 { get; set; }
        public string Shade10 { get; set; }
        public int? ColorArea1 { get; set; }
        public int? ColorArea2 { get; set; }
        public int? ColorArea3 { get; set; }
        public int? ColorArea4 { get; set; }
        public int? ColorArea5 { get; set; }
        public int? ColorArea6 { get; set; }
        public int? ColorArea7 { get; set; }
        public bool? Platen { get; set; }
        public bool? Rotary { get; set; }
        public bool? TearTape { get; set; }
        public bool? NoneBlk { get; set; }
        public bool? StanBlk { get; set; }
        public bool? SemiBlk { get; set; }
        public bool? ShipBlk { get; set; }
        public string BlockNo { get; set; }
        public string JoinMatNo { get; set; }
        public string SeparatMatNo { get; set; }
        public string RemarkInprocess { get; set; }
        public int? Hardship { get; set; }
        public string PdisStatus { get; set; }
        public bool TranStatus { get; set; }
        public bool SapStatus { get; set; }
        public string Alternative3 { get; set; }
        public string Alternative4 { get; set; }
        public string Alternative5 { get; set; }
        public string Alternative6 { get; set; }
        public string Alternative7 { get; set; }
        public string Alternative8 { get; set; }
        public bool RotateIn { get; set; }
        public bool RotateOut { get; set; }
        public int? StackHeight { get; set; }
        public int? SetupTm { get; set; }
        public int? SetupWaste { get; set; }
        public int? PrepareTm { get; set; }
        public int? PostTm { get; set; }
        public int? RunWaste { get; set; }
        public int? Human { get; set; }
        public int? ColorCount { get; set; }
        public bool? UnUpgradBoard { get; set; }
        public string ScoreType { get; set; }
        public double? ScoreGap { get; set; }
        public int? Coating { get; set; }
        public string BlockNo2 { get; set; }
        public string BlockNoPlant2 { get; set; }
        public string BlockNo3 { get; set; }
        public string BlockNoPlant3 { get; set; }
        public string BlockNo4 { get; set; }
        public string BlockNoPlant4 { get; set; }
        public string BlockNo5 { get; set; }
        public string BlockNoPlant5 { get; set; }
        public string PlateNo2 { get; set; }
        public string PlateNoPlant2 { get; set; }
        public string MylaNo2 { get; set; }
        public string MylaNoPlant2 { get; set; }
        public string PlateNo3 { get; set; }
        public string PlateNoPlant3 { get; set; }
        public string MylaNo3 { get; set; }
        public string MylaNoPlant3 { get; set; }
        public string PlateNo4 { get; set; }
        public string PlateNoPlant4 { get; set; }
        public string MylaNo4 { get; set; }
        public string MylaNoPlant4 { get; set; }
        public string PlateNo5 { get; set; }
        public string PlateNoPlant5 { get; set; }
        public string MylaNo5 { get; set; }
        public string MylaNoPlant5 { get; set; }
        public int? TearTapeQty { get; set; }
        public string TearTapeDistance { get; set; }
        public string MylaSize { get; set; }
        public List<Coating> Coatings { get; set; }
        public int? RepeatLength { get; set; }
        public string CustBarcodeNo { get; set; }
        public string QualitySpecs { get; set; }

        public string MachineDetail { get; set; }
        public string MachineColorDetail { get; set; }
    }
}
